import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>Lloyd Stevens</h1>
        </header>
        {children}
        <footer>
          <p>&copy; Lloyd Stevens 2023</p>
        </footer>
        </body>
    </html>
  )
}
